name: schedule

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1

      - name: weibo-trending-hot-search
        run: |
          git config --local user.email "${{ secrets.COMMIT_EMAIL }}"
          git config --local user.name "gorpeln"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          deno task start
          deno fmt
          git add .
          git commit -m "update by github action"
          git push
